export const SET_CONDITION_LIST = "SET_CONDITION_LIST";
export const ADD_URL_LIST = "ADD_URL_LIST";
export const UPDATE_LISTS = "UPDATE_LISTS";
export const REMOVE_LIST = "REMOVE_LIST";
export const TOGGLE_SAVED = "TOGGLED_SAVED";
export const RESET_STATE = "RESET_STATE";
export const SET_SELECTED_CONDITION = "SET_SELECTED_CONDITION";
